name: nerulibrary
description: "LiteraLib - A comprehensive digital library application for reading PDF and EPUB books"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  # Core Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Backend & Storage
  supabase_flutter: ^2.9.0
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  # HTTP & Network
  dio: ^5.3.0
  connectivity_plus: ^4.0.0

  # File & Storage
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  path: ^1.8.0
  crypto: ^3.0.3

  # Book Readers
  flutter_pdfview: ^1.3.0
  epubx: ^4.0.0

  # UI & Utils
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Navigation
  go_router: ^12.0.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0
  json_annotation: ^4.8.0
  json_serializable: ^6.7.0
  
  # Testing
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.0
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  test: ^1.24.0
  coverage: ^1.6.0
  fake_async: ^1.3.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  # Note: Font assets will be added when actual font files are available
